### ISSUE TITLE
Add ability descriptions to the wiki so one can get an overview

### ISSUE THREAD

**Issue by rapus95** [PrimordialMoros/Bending#25]
**Is your feature request related to a problem? Please describe.**
Annoyed of not being able to find ability information in your wiki.

**Describe the solution you'd like**
Add the ingame descriptions to the wiki.

**Describe alternatives you've considered**
Adding the mod to a game, starting it up, trying to understand the necessary commands.

**Additional context**
-

**Comment by PrimordialMoros** [comment]
Updated wiki docs with ability descriptions, instructions and default config
