### ISSUE TITLE
[Bending] Doesn't Work -  'boolean org.bukkit.entity.Player.isConnected()'

### ISSUE THREAD

**Issue by EdFabre** [PrimordialMoros/Bending#41]
**Is your feature request related to a problem? Please describe.**
Seems the plugin may have a bug. When commands are run, I see errors in the console. Also, actual bending doesn't work at all in game and spits out tons of errors.

![image](https://github.com/PrimordialMoros/Bending/assets/9345618/f9312aa9-7aad-4157-9a24-11d5a5dfc3d6)

Console Output
[bending_console_logs.txt](https://github.com/PrimordialMoros/Bending/files/13309010/bending_console_logs.txt)

**Comment by PrimordialMoros** [comment]
You are running an old paper build. You need at least 1.20.1 build #161 for Bending v3.4.0 or even better, update both to latest.
