### ISSUE TITLE
Incompatible with Floodgate on Fabric (and possibly other mods)

### ISSUE THREAD

**Issue by sylvxa** [PrimordialMoros/Bending#56]
### Bending Version

3.7.0

### Platform Details

Fabric Loader 0.15.7

### Mod/Plugin List

Floodgate
Bending
Fabric API

### Bug Description

The version of `cloud` (`2.0.0-beta.4`) used on 3.7.0 is incompatible with the version used by Floodgate (`1.8.4`) and several other mods. This can be worked around by downgrading to a specific commit of Bending between 3.5.0 and 3.6.0, before this dependency was bumped.

### Reproduction Steps

1. Install a mod using `cloud` version `1.8.4` (in this case Floodgate) and install Bending version `3.7.0`
2. Launch the server and see it lock up.

### Expected Behavior

Server boots up as normal with other mods.

### Logs and Configs

https://gist.github.com/sylvxa/f2873613f9ea7006b7015d2d4ebcf5cb

### Extra Info

I'm not sure whether using `1.8.4` or `2.0.0-beta.4` would be objectively better, but this could also be fixed if there was a way to keep the version of `cloud` separate from the one used in other mods. (that is outside the scope of my research, though)

**Comment by PrimordialMoros** [comment]
Due to the way fabric loads JIJ libraries you can't have 2 mods loading independent versions.
The solution would be for any cloud 1.x.x consumers to update to cloud v2.
They'll need to update to it when the next minecraft update happens anyway, so might as well do it now.
