### ISSUE TITLE
Dupe 

### ISSUE THREAD

**Issue by aqua-air** [PrimordialMoros/Bending#64]
### Bending Version

3.8.0

### Platform Details

Purpur 1.20.6 - v2219

### Mod/Plugin List

![2024-05-31_03 27 27](https://github.com/PrimordialMoros/Bending/assets/56618632/ef10df0a-7858-48fd-85bc-44d7b6cba680)

### Bug Description

Using EarthGlove spawns in a iron ingot that the user can spam and get free infinite iron.. craftable. It throws the iron ingot and then lets the user pick it up and keep it. I raised the cooldown really high to deal with this temporarily. 

### Reproduction Steps

1. ... Use paper/purpur 1.20.6 and bending
2. ... User Earthgove 
3. get free iron forever

### Expected Behavior

The ability doesn't spawn iron

### Extra Info

No logs appear in execution

**Comment by PrimordialMoros** [comment]
> I raised the cooldown really high to deal with this temporarily.

I recommend setting the permission node for earthglove (`bending.ability.earthglove`) to false until the updated version is released.
