### ISSUE TITLE
sinytra connector compatibility

### ISSUE THREAD

**Issue by OrdinaryCloverOC** [PrimordialMoros/Bending#74]
### Is your feature request related to a problem?

i'd like to use this on neoforge.

### Describe the solution you are proposing.

changing the method of managing localization (i do not know what this means, so i'll understand if it can't be done)

### Describe alternatives you've considered.

using fabric

### Other

https://github.com/Sinytra/Connector/issues/727

**Comment by PrimordialMoros** [comment]
While this specific issue is likely addressed by 027fbec7f015684918f8e0fe38c680ed504a94ff, there are no guarantees as Forge/NeoForge are not supported platforms at the time of writing this and it's almost certain there will be other problems.

I recommend you stick with one of the supported platforms (fabric or paper) instead and avoid any hybrids.

A case could be made for adding a neoforge platform implementation when it has matured but that's a different story.
